python main.py dataset=mvtec fe=wide sc=fca image_size=original tile_size=[9,9]
python main.py dataset=dtd fe=wide sc=fca image_size=original tile_size=[9,9]
python main.py dataset=btad fe=wide sc=fca image_size=original tile_size=[9,9]
python main.py dataset=wft fe=wide sc=fca image_size=original tile_size=[9,9]
python main.py dataset=wfdd fe=wide sc=fca image_size=original tile_size=[9,9]