name: beta07
data_manager:
  _target_: data_loaders.StandardFormatDataset
  data_dir: ${hydra:runtime.cwd}/datasets/Beta07
  out_dir: ${hydra:runtime.output_dir}
  paddings: [20]
  objects: ['carpet', 'grid', 'leather', 'tile', 'wood']
