name: 0.9
data_manager:
  _target_: data_loaders.StandardFormatDataset
  data_dir: ${hydra:runtime.cwd}/datasets/Beta_0.9
  out_dir: ${hydra:runtime.output_dir}
  paddings: [100]
  objects: ['carpet', 'grid', 'leather', 'tile', 'wood']
